/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as StudyPlanRouteImport } from './routes/study-plan'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PastPaperAnalyzerRouteImport } from './routes/past-paper-analyzer'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MockTestRouteImport } from './routes/mock-test'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChaptersRouteImport } from './routes/chapters'
import { Route as BoardQuestionsRouteImport } from './routes/board-questions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiGeneratorRouteImport } from './routes/ai-generator'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsSlugRouteImport } from './routes/subjects.$slug'
import { Route as ResultAttemptIdRouteImport } from './routes/result.$attemptId'
import { Route as PracticeChapterIdRouteImport } from './routes/practice.$chapterId'
import { Route as MockTestSetupRouteImport } from './routes/mock-test.setup'
import { Route as MockTestMockIdRouteImport } from './routes/mock-test.$mockId'
import { Route as DemoGravitationRouteImport } from './routes/demo.gravitation'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as AdminQuestionReviewRouteImport } from './routes/admin.question-review'
import { Route as AdminBoardQuestionsRouteImport } from './routes/admin.board-questions'
import { Route as ChaptersChapterIdIndexRouteImport } from './routes/chapters.$chapterId.index'
import { Route as ChaptersChapterIdBoardQuestionsRouteImport } from './routes/chapters.$chapterId.board-questions'
import { Route as ChaptersChapterIdBoardPracticeRouteImport } from './routes/chapters.$chapterId.board-practice'

const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyPlanRoute = StudyPlanRouteImport.update({
  id: '/study-plan',
  path: '/study-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PastPaperAnalyzerRoute = PastPaperAnalyzerRouteImport.update({
  id: '/past-paper-analyzer',
  path: '/past-paper-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestRoute = MockTestRouteImport.update({
  id: '/mock-test',
  path: '/mock-test',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersRoute = ChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardQuestionsRoute = BoardQuestionsRouteImport.update({
  id: '/board-questions',
  path: '/board-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiGeneratorRoute = AiGeneratorRouteImport.update({
  id: '/ai-generator',
  path: '/ai-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSlugRoute = SubjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SubjectsRoute,
} as any)
const ResultAttemptIdRoute = ResultAttemptIdRouteImport.update({
  id: '/result/$attemptId',
  path: '/result/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeChapterIdRoute = PracticeChapterIdRouteImport.update({
  id: '/$chapterId',
  path: '/$chapterId',
  getParentRoute: () => PracticeRoute,
} as any)
const MockTestSetupRoute = MockTestSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => MockTestRoute,
} as any)
const MockTestMockIdRoute = MockTestMockIdRouteImport.update({
  id: '/$mockId',
  path: '/$mockId',
  getParentRoute: () => MockTestRoute,
} as any)
const DemoGravitationRoute = DemoGravitationRouteImport.update({
  id: '/demo/gravitation',
  path: '/demo/gravitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionReviewRoute = AdminQuestionReviewRouteImport.update({
  id: '/question-review',
  path: '/question-review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBoardQuestionsRoute = AdminBoardQuestionsRouteImport.update({
  id: '/board-questions',
  path: '/board-questions',
  getParentRoute: () => AdminRoute,
} as any)
const ChaptersChapterIdIndexRoute = ChaptersChapterIdIndexRouteImport.update({
  id: '/$chapterId/',
  path: '/$chapterId/',
  getParentRoute: () => ChaptersRoute,
} as any)
const ChaptersChapterIdBoardQuestionsRoute =
  ChaptersChapterIdBoardQuestionsRouteImport.update({
    id: '/$chapterId/board-questions',
    path: '/$chapterId/board-questions',
    getParentRoute: () => ChaptersRoute,
  } as any)
const ChaptersChapterIdBoardPracticeRoute =
  ChaptersChapterIdBoardPracticeRouteImport.update({
    id: '/$chapterId/board-practice',
    path: '/$chapterId/board-practice',
    getParentRoute: () => ChaptersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-generator': typeof AiGeneratorRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/board-questions': typeof BoardQuestionsRoute
  '/chapters': typeof ChaptersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/mock-test': typeof MockTestRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/past-paper-analyzer': typeof PastPaperAnalyzerRoute
  '/practice': typeof PracticeRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/study-plan': typeof StudyPlanRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/admin/board-questions': typeof AdminBoardQuestionsRoute
  '/admin/question-review': typeof AdminQuestionReviewRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/demo/gravitation': typeof DemoGravitationRoute
  '/mock-test/$mockId': typeof MockTestMockIdRoute
  '/mock-test/setup': typeof MockTestSetupRoute
  '/practice/$chapterId': typeof PracticeChapterIdRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
  '/chapters/$chapterId/board-practice': typeof ChaptersChapterIdBoardPracticeRoute
  '/chapters/$chapterId/board-questions': typeof ChaptersChapterIdBoardQuestionsRoute
  '/chapters/$chapterId/': typeof ChaptersChapterIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-generator': typeof AiGeneratorRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/board-questions': typeof BoardQuestionsRoute
  '/chapters': typeof ChaptersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/mock-test': typeof MockTestRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/past-paper-analyzer': typeof PastPaperAnalyzerRoute
  '/practice': typeof PracticeRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/study-plan': typeof StudyPlanRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/admin/board-questions': typeof AdminBoardQuestionsRoute
  '/admin/question-review': typeof AdminQuestionReviewRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/demo/gravitation': typeof DemoGravitationRoute
  '/mock-test/$mockId': typeof MockTestMockIdRoute
  '/mock-test/setup': typeof MockTestSetupRoute
  '/practice/$chapterId': typeof PracticeChapterIdRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
  '/chapters/$chapterId/board-practice': typeof ChaptersChapterIdBoardPracticeRoute
  '/chapters/$chapterId/board-questions': typeof ChaptersChapterIdBoardQuestionsRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-generator': typeof AiGeneratorRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/board-questions': typeof BoardQuestionsRoute
  '/chapters': typeof ChaptersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/mock-test': typeof MockTestRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/past-paper-analyzer': typeof PastPaperAnalyzerRoute
  '/practice': typeof PracticeRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/study-plan': typeof StudyPlanRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/admin/board-questions': typeof AdminBoardQuestionsRoute
  '/admin/question-review': typeof AdminQuestionReviewRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/demo/gravitation': typeof DemoGravitationRoute
  '/mock-test/$mockId': typeof MockTestMockIdRoute
  '/mock-test/setup': typeof MockTestSetupRoute
  '/practice/$chapterId': typeof PracticeChapterIdRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
  '/chapters/$chapterId/board-practice': typeof ChaptersChapterIdBoardPracticeRoute
  '/chapters/$chapterId/board-questions': typeof ChaptersChapterIdBoardQuestionsRoute
  '/chapters/$chapterId/': typeof ChaptersChapterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-generator'
    | '/analytics'
    | '/auth'
    | '/board-questions'
    | '/chapters'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/mock-test'
    | '/onboarding'
    | '/past-paper-analyzer'
    | '/practice'
    | '/profile'
    | '/reset-password'
    | '/resources'
    | '/study-plan'
    | '/subjects'
    | '/admin/board-questions'
    | '/admin/question-review'
    | '/admin/questions'
    | '/demo/gravitation'
    | '/mock-test/$mockId'
    | '/mock-test/setup'
    | '/practice/$chapterId'
    | '/result/$attemptId'
    | '/subjects/$slug'
    | '/chapters/$chapterId/board-practice'
    | '/chapters/$chapterId/board-questions'
    | '/chapters/$chapterId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-generator'
    | '/analytics'
    | '/auth'
    | '/board-questions'
    | '/chapters'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/mock-test'
    | '/onboarding'
    | '/past-paper-analyzer'
    | '/practice'
    | '/profile'
    | '/reset-password'
    | '/resources'
    | '/study-plan'
    | '/subjects'
    | '/admin/board-questions'
    | '/admin/question-review'
    | '/admin/questions'
    | '/demo/gravitation'
    | '/mock-test/$mockId'
    | '/mock-test/setup'
    | '/practice/$chapterId'
    | '/result/$attemptId'
    | '/subjects/$slug'
    | '/chapters/$chapterId/board-practice'
    | '/chapters/$chapterId/board-questions'
    | '/chapters/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-generator'
    | '/analytics'
    | '/auth'
    | '/board-questions'
    | '/chapters'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/mock-test'
    | '/onboarding'
    | '/past-paper-analyzer'
    | '/practice'
    | '/profile'
    | '/reset-password'
    | '/resources'
    | '/study-plan'
    | '/subjects'
    | '/admin/board-questions'
    | '/admin/question-review'
    | '/admin/questions'
    | '/demo/gravitation'
    | '/mock-test/$mockId'
    | '/mock-test/setup'
    | '/practice/$chapterId'
    | '/result/$attemptId'
    | '/subjects/$slug'
    | '/chapters/$chapterId/board-practice'
    | '/chapters/$chapterId/board-questions'
    | '/chapters/$chapterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiGeneratorRoute: typeof AiGeneratorRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  BoardQuestionsRoute: typeof BoardQuestionsRoute
  ChaptersRoute: typeof ChaptersRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  MockTestRoute: typeof MockTestRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PastPaperAnalyzerRoute: typeof PastPaperAnalyzerRoute
  PracticeRoute: typeof PracticeRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  StudyPlanRoute: typeof StudyPlanRoute
  SubjectsRoute: typeof SubjectsRouteWithChildren
  DemoGravitationRoute: typeof DemoGravitationRoute
  ResultAttemptIdRoute: typeof ResultAttemptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-plan': {
      id: '/study-plan'
      path: '/study-plan'
      fullPath: '/study-plan'
      preLoaderRoute: typeof StudyPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-paper-analyzer': {
      id: '/past-paper-analyzer'
      path: '/past-paper-analyzer'
      fullPath: '/past-paper-analyzer'
      preLoaderRoute: typeof PastPaperAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-test': {
      id: '/mock-test'
      path: '/mock-test'
      fullPath: '/mock-test'
      preLoaderRoute: typeof MockTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters': {
      id: '/chapters'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board-questions': {
      id: '/board-questions'
      path: '/board-questions'
      fullPath: '/board-questions'
      preLoaderRoute: typeof BoardQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-generator': {
      id: '/ai-generator'
      path: '/ai-generator'
      fullPath: '/ai-generator'
      preLoaderRoute: typeof AiGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$slug': {
      id: '/subjects/$slug'
      path: '/$slug'
      fullPath: '/subjects/$slug'
      preLoaderRoute: typeof SubjectsSlugRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/result/$attemptId': {
      id: '/result/$attemptId'
      path: '/result/$attemptId'
      fullPath: '/result/$attemptId'
      preLoaderRoute: typeof ResultAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$chapterId': {
      id: '/practice/$chapterId'
      path: '/$chapterId'
      fullPath: '/practice/$chapterId'
      preLoaderRoute: typeof PracticeChapterIdRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/mock-test/setup': {
      id: '/mock-test/setup'
      path: '/setup'
      fullPath: '/mock-test/setup'
      preLoaderRoute: typeof MockTestSetupRouteImport
      parentRoute: typeof MockTestRoute
    }
    '/mock-test/$mockId': {
      id: '/mock-test/$mockId'
      path: '/$mockId'
      fullPath: '/mock-test/$mockId'
      preLoaderRoute: typeof MockTestMockIdRouteImport
      parentRoute: typeof MockTestRoute
    }
    '/demo/gravitation': {
      id: '/demo/gravitation'
      path: '/demo/gravitation'
      fullPath: '/demo/gravitation'
      preLoaderRoute: typeof DemoGravitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/question-review': {
      id: '/admin/question-review'
      path: '/question-review'
      fullPath: '/admin/question-review'
      preLoaderRoute: typeof AdminQuestionReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/board-questions': {
      id: '/admin/board-questions'
      path: '/board-questions'
      fullPath: '/admin/board-questions'
      preLoaderRoute: typeof AdminBoardQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/chapters/$chapterId/': {
      id: '/chapters/$chapterId/'
      path: '/$chapterId'
      fullPath: '/chapters/$chapterId/'
      preLoaderRoute: typeof ChaptersChapterIdIndexRouteImport
      parentRoute: typeof ChaptersRoute
    }
    '/chapters/$chapterId/board-questions': {
      id: '/chapters/$chapterId/board-questions'
      path: '/$chapterId/board-questions'
      fullPath: '/chapters/$chapterId/board-questions'
      preLoaderRoute: typeof ChaptersChapterIdBoardQuestionsRouteImport
      parentRoute: typeof ChaptersRoute
    }
    '/chapters/$chapterId/board-practice': {
      id: '/chapters/$chapterId/board-practice'
      path: '/$chapterId/board-practice'
      fullPath: '/chapters/$chapterId/board-practice'
      preLoaderRoute: typeof ChaptersChapterIdBoardPracticeRouteImport
      parentRoute: typeof ChaptersRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBoardQuestionsRoute: typeof AdminBoardQuestionsRoute
  AdminQuestionReviewRoute: typeof AdminQuestionReviewRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBoardQuestionsRoute: AdminBoardQuestionsRoute,
  AdminQuestionReviewRoute: AdminQuestionReviewRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ChaptersRouteChildren {
  ChaptersChapterIdBoardPracticeRoute: typeof ChaptersChapterIdBoardPracticeRoute
  ChaptersChapterIdBoardQuestionsRoute: typeof ChaptersChapterIdBoardQuestionsRoute
  ChaptersChapterIdIndexRoute: typeof ChaptersChapterIdIndexRoute
}

const ChaptersRouteChildren: ChaptersRouteChildren = {
  ChaptersChapterIdBoardPracticeRoute: ChaptersChapterIdBoardPracticeRoute,
  ChaptersChapterIdBoardQuestionsRoute: ChaptersChapterIdBoardQuestionsRoute,
  ChaptersChapterIdIndexRoute: ChaptersChapterIdIndexRoute,
}

const ChaptersRouteWithChildren = ChaptersRoute._addFileChildren(
  ChaptersRouteChildren,
)

interface MockTestRouteChildren {
  MockTestMockIdRoute: typeof MockTestMockIdRoute
  MockTestSetupRoute: typeof MockTestSetupRoute
}

const MockTestRouteChildren: MockTestRouteChildren = {
  MockTestMockIdRoute: MockTestMockIdRoute,
  MockTestSetupRoute: MockTestSetupRoute,
}

const MockTestRouteWithChildren = MockTestRoute._addFileChildren(
  MockTestRouteChildren,
)

interface PracticeRouteChildren {
  PracticeChapterIdRoute: typeof PracticeChapterIdRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeChapterIdRoute: PracticeChapterIdRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

interface SubjectsRouteChildren {
  SubjectsSlugRoute: typeof SubjectsSlugRoute
}

const SubjectsRouteChildren: SubjectsRouteChildren = {
  SubjectsSlugRoute: SubjectsSlugRoute,
}

const SubjectsRouteWithChildren = SubjectsRoute._addFileChildren(
  SubjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AiGeneratorRoute: AiGeneratorRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  BoardQuestionsRoute: BoardQuestionsRoute,
  ChaptersRoute: ChaptersRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  MockTestRoute: MockTestRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PastPaperAnalyzerRoute: PastPaperAnalyzerRoute,
  PracticeRoute: PracticeRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  StudyPlanRoute: StudyPlanRoute,
  SubjectsRoute: SubjectsRouteWithChildren,
  DemoGravitationRoute: DemoGravitationRoute,
  ResultAttemptIdRoute: ResultAttemptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
