/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MockTestRouteImport } from './routes/mock-test'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChaptersRouteImport } from './routes/chapters'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsSlugRouteImport } from './routes/subjects.$slug'
import { Route as ResultAttemptIdRouteImport } from './routes/result.$attemptId'
import { Route as PracticeChapterIdRouteImport } from './routes/practice.$chapterId'
import { Route as AdminQuestionReviewRouteImport } from './routes/admin.question-review'

const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestRoute = MockTestRouteImport.update({
  id: '/mock-test',
  path: '/mock-test',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersRoute = ChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSlugRoute = SubjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SubjectsRoute,
} as any)
const ResultAttemptIdRoute = ResultAttemptIdRouteImport.update({
  id: '/result/$attemptId',
  path: '/result/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeChapterIdRoute = PracticeChapterIdRouteImport.update({
  id: '/$chapterId',
  path: '/$chapterId',
  getParentRoute: () => PracticeRoute,
} as any)
const AdminQuestionReviewRoute = AdminQuestionReviewRouteImport.update({
  id: '/question-review',
  path: '/question-review',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/chapters': typeof ChaptersRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/mock-test': typeof MockTestRoute
  '/onboarding': typeof OnboardingRoute
  '/practice': typeof PracticeRouteWithChildren
  '/profile': typeof ProfileRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/admin/question-review': typeof AdminQuestionReviewRoute
  '/practice/$chapterId': typeof PracticeChapterIdRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/chapters': typeof ChaptersRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/mock-test': typeof MockTestRoute
  '/onboarding': typeof OnboardingRoute
  '/practice': typeof PracticeRouteWithChildren
  '/profile': typeof ProfileRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/admin/question-review': typeof AdminQuestionReviewRoute
  '/practice/$chapterId': typeof PracticeChapterIdRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/chapters': typeof ChaptersRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/mock-test': typeof MockTestRoute
  '/onboarding': typeof OnboardingRoute
  '/practice': typeof PracticeRouteWithChildren
  '/profile': typeof ProfileRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/admin/question-review': typeof AdminQuestionReviewRoute
  '/practice/$chapterId': typeof PracticeChapterIdRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/chapters'
    | '/dashboard'
    | '/history'
    | '/mock-test'
    | '/onboarding'
    | '/practice'
    | '/profile'
    | '/subjects'
    | '/admin/question-review'
    | '/practice/$chapterId'
    | '/result/$attemptId'
    | '/subjects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/chapters'
    | '/dashboard'
    | '/history'
    | '/mock-test'
    | '/onboarding'
    | '/practice'
    | '/profile'
    | '/subjects'
    | '/admin/question-review'
    | '/practice/$chapterId'
    | '/result/$attemptId'
    | '/subjects/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/chapters'
    | '/dashboard'
    | '/history'
    | '/mock-test'
    | '/onboarding'
    | '/practice'
    | '/profile'
    | '/subjects'
    | '/admin/question-review'
    | '/practice/$chapterId'
    | '/result/$attemptId'
    | '/subjects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  ChaptersRoute: typeof ChaptersRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  MockTestRoute: typeof MockTestRoute
  OnboardingRoute: typeof OnboardingRoute
  PracticeRoute: typeof PracticeRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SubjectsRoute: typeof SubjectsRouteWithChildren
  ResultAttemptIdRoute: typeof ResultAttemptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-test': {
      id: '/mock-test'
      path: '/mock-test'
      fullPath: '/mock-test'
      preLoaderRoute: typeof MockTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters': {
      id: '/chapters'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$slug': {
      id: '/subjects/$slug'
      path: '/$slug'
      fullPath: '/subjects/$slug'
      preLoaderRoute: typeof SubjectsSlugRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/result/$attemptId': {
      id: '/result/$attemptId'
      path: '/result/$attemptId'
      fullPath: '/result/$attemptId'
      preLoaderRoute: typeof ResultAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$chapterId': {
      id: '/practice/$chapterId'
      path: '/$chapterId'
      fullPath: '/practice/$chapterId'
      preLoaderRoute: typeof PracticeChapterIdRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/admin/question-review': {
      id: '/admin/question-review'
      path: '/question-review'
      fullPath: '/admin/question-review'
      preLoaderRoute: typeof AdminQuestionReviewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminQuestionReviewRoute: typeof AdminQuestionReviewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminQuestionReviewRoute: AdminQuestionReviewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PracticeRouteChildren {
  PracticeChapterIdRoute: typeof PracticeChapterIdRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeChapterIdRoute: PracticeChapterIdRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

interface SubjectsRouteChildren {
  SubjectsSlugRoute: typeof SubjectsSlugRoute
}

const SubjectsRouteChildren: SubjectsRouteChildren = {
  SubjectsSlugRoute: SubjectsSlugRoute,
}

const SubjectsRouteWithChildren = SubjectsRoute._addFileChildren(
  SubjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  ChaptersRoute: ChaptersRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  MockTestRoute: MockTestRoute,
  OnboardingRoute: OnboardingRoute,
  PracticeRoute: PracticeRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SubjectsRoute: SubjectsRouteWithChildren,
  ResultAttemptIdRoute: ResultAttemptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
