-- Seed chapter/unit rows for the HSC subjects introduced in Phase 2.
-- This migration is intentionally idempotent and does not modify existing rows.

WITH chapter_seed(subject_slug, order_index, name) AS (
  VALUES
    -- Common compulsory subjects
    ('bangla', 1, 'Bangla 1st Paper: Prose'),
    ('bangla', 2, 'Bangla 1st Paper: Poetry'),
    ('bangla', 3, 'Bangla 1st Paper: Novel'),
    ('bangla', 4, 'Bangla 1st Paper: Drama'),
    ('bangla', 5, 'Bangla 2nd Paper: Grammar'),
    ('bangla', 6, 'Bangla 2nd Paper: Composition'),

    ('english', 1, 'English 1st Paper: Reading Comprehension'),
    ('english', 2, 'English 1st Paper: Vocabulary'),
    ('english', 3, 'English 1st Paper: Rearranging'),
    ('english', 4, 'English 1st Paper: Summary Writing'),
    ('english', 5, 'English 1st Paper: Paragraph and Story Writing'),
    ('english', 6, 'English 1st Paper: Graph and Chart Writing'),
    ('english', 7, 'English 2nd Paper: Grammar'),
    ('english', 8, 'English 2nd Paper: Composition'),

    ('ict', 1, 'ICT: World and Bangladesh Perspective'),
    ('ict', 2, 'Communication Systems and Networking'),
    ('ict', 3, 'Number Systems and Digital Devices'),
    ('ict', 4, 'Web Design and HTML'),
    ('ict', 5, 'Programming Language'),
    ('ict', 6, 'Database Management System'),

    -- Science subjects
    ('physics-1', 1, 'Physical World and Measurement'),
    ('physics-1', 2, 'Vector'),
    ('physics-1', 3, 'Dynamics'),
    ('physics-1', 4, 'Newtonian Mechanics'),
    ('physics-1', 5, 'Work, Energy and Power'),
    ('physics-1', 6, 'Gravitation and Gravity'),
    ('physics-1', 7, 'Structural Properties of Matter'),
    ('physics-1', 8, 'Periodic Motion'),
    ('physics-1', 9, 'Waves'),
    ('physics-1', 10, 'Ideal Gas and Kinetic Theory of Gases'),

    ('physics-2', 1, 'Thermodynamics'),
    ('physics-2', 2, 'Static Electricity'),
    ('physics-2', 3, 'Current Electricity'),
    ('physics-2', 4, 'Magnetic Effect of Current and Magnetism'),
    ('physics-2', 5, 'Electromagnetic Induction and Alternating Current'),
    ('physics-2', 6, 'Geometrical Optics'),
    ('physics-2', 7, 'Physical Optics'),
    ('physics-2', 8, 'Introduction to Modern Physics'),
    ('physics-2', 9, 'Atomic Model and Nuclear Physics'),
    ('physics-2', 10, 'Semiconductor and Electronics'),
    ('physics-2', 11, 'Astronomy'),

    ('chemistry-1', 1, 'Safe Use of Laboratory'),
    ('chemistry-1', 2, 'Qualitative Chemistry'),
    ('chemistry-1', 3, 'Periodic Properties of Elements and Chemical Bonding'),
    ('chemistry-1', 4, 'Chemical Changes'),
    ('chemistry-1', 5, 'Applied Chemistry'),

    ('chemistry-2', 1, 'Environmental Chemistry'),
    ('chemistry-2', 2, 'Organic Chemistry'),
    ('chemistry-2', 3, 'Quantitative Chemistry'),
    ('chemistry-2', 4, 'Electrochemistry'),
    ('chemistry-2', 5, 'Economic Chemistry'),

    ('biology-1', 1, 'Cell and Its Structure'),
    ('biology-1', 2, 'Cell Division'),
    ('biology-1', 3, 'Cell Chemistry'),
    ('biology-1', 4, 'Microorganisms'),
    ('biology-1', 5, 'Algae and Fungi'),
    ('biology-1', 6, 'Bryophyta and Pteridophyta'),
    ('biology-1', 7, 'Gymnosperms and Angiosperms'),
    ('biology-1', 8, 'Tissue and Tissue System'),
    ('biology-1', 9, 'Plant Physiology'),
    ('biology-1', 10, 'Plant Reproduction'),
    ('biology-1', 11, 'Biotechnology'),
    ('biology-1', 12, 'Ecology, Distribution and Conservation'),

    ('biology-2', 1, 'Animal Diversity and Classification'),
    ('biology-2', 2, 'Animal Identity: Hydra'),
    ('biology-2', 3, 'Animal Identity: Grasshopper'),
    ('biology-2', 4, 'Human Physiology: Digestion and Absorption'),
    ('biology-2', 5, 'Human Physiology: Blood and Circulation'),
    ('biology-2', 6, 'Human Physiology: Respiration and Breathing'),
    ('biology-2', 7, 'Human Physiology: Excretion'),
    ('biology-2', 8, 'Human Physiology: Movement and Locomotion'),
    ('biology-2', 9, 'Human Physiology: Coordination and Control'),
    ('biology-2', 10, 'Human Reproduction and Development'),
    ('biology-2', 11, 'Genetics and Evolution'),
    ('biology-2', 12, 'Animal Behavior'),

    ('higher-math-1', 1, 'Matrices and Determinants'),
    ('higher-math-1', 2, 'Vector'),
    ('higher-math-1', 3, 'Straight Lines'),
    ('higher-math-1', 4, 'The Circle'),
    ('higher-math-1', 5, 'Permutations and Combinations'),
    ('higher-math-1', 6, 'Trigonometric Ratios'),
    ('higher-math-1', 7, 'Trigonometric Ratios of Associated Angles'),
    ('higher-math-1', 8, 'Functions and Graphs of Functions'),
    ('higher-math-1', 9, 'Differentiation'),
    ('higher-math-1', 10, 'Integration'),

    ('higher-math-2', 1, 'Complex Numbers'),
    ('higher-math-2', 2, 'Polynomials and Polynomial Equations'),
    ('higher-math-2', 3, 'Conics'),
    ('higher-math-2', 4, 'Inverse Trigonometric Functions and Trigonometric Equations'),
    ('higher-math-2', 5, 'Statics'),
    ('higher-math-2', 6, 'Motion of Particles in a Plane'),
    ('higher-math-2', 7, 'Linear Programming'),
    ('higher-math-2', 8, 'Probability'),
    ('higher-math-2', 9, 'Statistics'),

    -- Business Studies subjects
    ('accounting-1', 1, 'Introduction to Accounting'),
    ('accounting-1', 2, 'Accounting Equation and Transactions'),
    ('accounting-1', 3, 'Journal'),
    ('accounting-1', 4, 'Ledger'),
    ('accounting-1', 5, 'Cash Book'),
    ('accounting-1', 6, 'Trial Balance'),
    ('accounting-1', 7, 'Financial Statements'),
    ('accounting-1', 8, 'Adjusting Entries'),
    ('accounting-1', 9, 'Depreciation'),
    ('accounting-1', 10, 'Reserves and Provisions'),
    ('accounting-1', 11, 'Single Entry System'),
    ('accounting-1', 12, 'Accounting for Non-Profit Organizations'),

    ('accounting-2', 1, 'Partnership Accounts'),
    ('accounting-2', 2, 'Company Accounts'),
    ('accounting-2', 3, 'Accounting for Shares and Debentures'),
    ('accounting-2', 4, 'Cost Accounting'),
    ('accounting-2', 5, 'Management Accounting'),
    ('accounting-2', 6, 'Financial Statement Analysis'),
    ('accounting-2', 7, 'Ratio Analysis'),
    ('accounting-2', 8, 'Cash Flow Statement'),
    ('accounting-2', 9, 'Budgetary Control'),
    ('accounting-2', 10, 'Standard Costing'),

    ('business-organization-1', 1, 'Nature and Environment of Business'),
    ('business-organization-1', 2, 'Business Ownership'),
    ('business-organization-1', 3, 'Joint Stock Company'),
    ('business-organization-1', 4, 'Cooperative Society'),
    ('business-organization-1', 5, 'State Enterprise'),
    ('business-organization-1', 6, 'Small Business'),
    ('business-organization-1', 7, 'Business Plan'),
    ('business-organization-1', 8, 'Entrepreneurship'),
    ('business-organization-1', 9, 'Social Responsibility of Business'),
    ('business-organization-1', 10, 'Business Communication'),

    ('business-organization-2', 1, 'Introduction to Management'),
    ('business-organization-2', 2, 'Planning'),
    ('business-organization-2', 3, 'Organizing'),
    ('business-organization-2', 4, 'Staffing'),
    ('business-organization-2', 5, 'Leadership'),
    ('business-organization-2', 6, 'Motivation'),
    ('business-organization-2', 7, 'Coordination'),
    ('business-organization-2', 8, 'Controlling'),
    ('business-organization-2', 9, 'Production Management'),
    ('business-organization-2', 10, 'Marketing Management'),

    ('finance-banking-insurance-1', 1, 'Introduction to Finance'),
    ('finance-banking-insurance-1', 2, 'Financial Planning'),
    ('finance-banking-insurance-1', 3, 'Time Value of Money'),
    ('finance-banking-insurance-1', 4, 'Risk and Return'),
    ('finance-banking-insurance-1', 5, 'Cost of Capital'),
    ('finance-banking-insurance-1', 6, 'Capital Budgeting'),
    ('finance-banking-insurance-1', 7, 'Working Capital Management'),
    ('finance-banking-insurance-1', 8, 'Sources of Finance'),
    ('finance-banking-insurance-1', 9, 'Financial Markets'),
    ('finance-banking-insurance-1', 10, 'Securities and Investment'),

    ('finance-banking-insurance-2', 1, 'Introduction to Banking'),
    ('finance-banking-insurance-2', 2, 'Central Bank'),
    ('finance-banking-insurance-2', 3, 'Commercial Bank'),
    ('finance-banking-insurance-2', 4, 'Bank Accounts'),
    ('finance-banking-insurance-2', 5, 'Negotiable Instruments'),
    ('finance-banking-insurance-2', 6, 'Digital Banking'),
    ('finance-banking-insurance-2', 7, 'Introduction to Insurance'),
    ('finance-banking-insurance-2', 8, 'Life Insurance'),
    ('finance-banking-insurance-2', 9, 'Fire and Marine Insurance'),
    ('finance-banking-insurance-2', 10, 'Islamic Banking and Insurance'),

    ('production-management-marketing-1', 1, 'Introduction to Production Management'),
    ('production-management-marketing-1', 2, 'Product Design'),
    ('production-management-marketing-1', 3, 'Factory Location'),
    ('production-management-marketing-1', 4, 'Plant Layout'),
    ('production-management-marketing-1', 5, 'Work Study'),
    ('production-management-marketing-1', 6, 'Inventory Management'),
    ('production-management-marketing-1', 7, 'Quality Control'),
    ('production-management-marketing-1', 8, 'Productivity'),
    ('production-management-marketing-1', 9, 'Operations Research'),

    ('production-management-marketing-2', 1, 'Introduction to Marketing'),
    ('production-management-marketing-2', 2, 'Consumer Behavior'),
    ('production-management-marketing-2', 3, 'Market Segmentation'),
    ('production-management-marketing-2', 4, 'Product'),
    ('production-management-marketing-2', 5, 'Pricing'),
    ('production-management-marketing-2', 6, 'Distribution'),
    ('production-management-marketing-2', 7, 'Promotion'),
    ('production-management-marketing-2', 8, 'Branding'),
    ('production-management-marketing-2', 9, 'Service Marketing'),
    ('production-management-marketing-2', 10, 'International Marketing'),

    -- Humanities subjects
    ('economics-1', 1, 'Introduction to Economics'),
    ('economics-1', 2, 'Utility, Demand and Supply'),
    ('economics-1', 3, 'Elasticity'),
    ('economics-1', 4, 'Production'),
    ('economics-1', 5, 'Cost and Revenue'),
    ('economics-1', 6, 'Market'),
    ('economics-1', 7, 'Factor Pricing'),
    ('economics-1', 8, 'National Income'),
    ('economics-1', 9, 'Money and Banking'),

    ('economics-2', 1, 'Introduction to Bangladesh Economy'),
    ('economics-2', 2, 'Agriculture in Bangladesh'),
    ('economics-2', 3, 'Industry in Bangladesh'),
    ('economics-2', 4, 'Population and Human Resources'),
    ('economics-2', 5, 'Public Finance'),
    ('economics-2', 6, 'Inflation'),
    ('economics-2', 7, 'International Trade'),
    ('economics-2', 8, 'Economic Development'),
    ('economics-2', 9, 'Planning and Sustainable Development'),

    ('civics-1', 1, 'Civics and Citizenship'),
    ('civics-1', 2, 'State'),
    ('civics-1', 3, 'Government'),
    ('civics-1', 4, 'Constitution'),
    ('civics-1', 5, 'Citizenship'),
    ('civics-1', 6, 'Law, Liberty and Equality'),
    ('civics-1', 7, 'Political Parties'),
    ('civics-1', 8, 'Public Opinion'),
    ('civics-1', 9, 'Election'),
    ('civics-1', 10, 'Constitution of Bangladesh'),

    ('civics-2', 1, 'Local Government'),
    ('civics-2', 2, 'Bureaucracy'),
    ('civics-2', 3, 'Judiciary'),
    ('civics-2', 4, 'Democracy'),
    ('civics-2', 5, 'Human Rights'),
    ('civics-2', 6, 'Good Governance'),
    ('civics-2', 7, 'International Relations'),
    ('civics-2', 8, 'United Nations'),
    ('civics-2', 9, 'Foreign Policy of Bangladesh'),

    ('sociology-1', 1, 'Introduction to Sociology'),
    ('sociology-1', 2, 'Culture'),
    ('sociology-1', 3, 'Socialization'),
    ('sociology-1', 4, 'Society'),
    ('sociology-1', 5, 'Social Groups and Organizations'),
    ('sociology-1', 6, 'Social Stratification'),
    ('sociology-1', 7, 'Social Institutions'),
    ('sociology-1', 8, 'Social Change'),
    ('sociology-1', 9, 'Deviance and Social Control'),
    ('sociology-1', 10, 'Social Research'),

    ('sociology-2', 1, 'Bangladesh Society'),
    ('sociology-2', 2, 'Rural and Urban Society'),
    ('sociology-2', 3, 'Population'),
    ('sociology-2', 4, 'Family and Marriage'),
    ('sociology-2', 5, 'Education'),
    ('sociology-2', 6, 'Poverty'),
    ('sociology-2', 7, 'Gender and Society'),
    ('sociology-2', 8, 'Environment and Society'),
    ('sociology-2', 9, 'Development'),
    ('sociology-2', 10, 'Social Problems in Bangladesh'),

    ('history-1', 1, 'Ancient Bengal'),
    ('history-1', 2, 'Early Medieval Bengal'),
    ('history-1', 3, 'Bengal Sultanate'),
    ('history-1', 4, 'Mughal Bengal'),
    ('history-1', 5, 'British East India Company Rule'),
    ('history-1', 6, 'Social and Religious Reform Movements'),
    ('history-1', 7, 'Sepoy Revolt of 1857'),
    ('history-1', 8, 'Partition of Bengal'),
    ('history-1', 9, 'Language Movement'),
    ('history-1', 10, 'Liberation War of Bangladesh'),

    ('history-2', 1, 'Industrial Revolution'),
    ('history-2', 2, 'American Revolution'),
    ('history-2', 3, 'French Revolution'),
    ('history-2', 4, 'Russian Revolution'),
    ('history-2', 5, 'First World War'),
    ('history-2', 6, 'League of Nations'),
    ('history-2', 7, 'Second World War'),
    ('history-2', 8, 'United Nations'),
    ('history-2', 9, 'Cold War'),
    ('history-2', 10, 'Globalization'),

    ('geography-1', 1, 'Physical Geography'),
    ('geography-1', 2, 'The Earth'),
    ('geography-1', 3, 'Landforms'),
    ('geography-1', 4, 'Weather and Climate'),
    ('geography-1', 5, 'Oceanography'),
    ('geography-1', 6, 'Natural Hazards'),
    ('geography-1', 7, 'Map Reading'),
    ('geography-1', 8, 'Physical Geography of Bangladesh'),

    ('geography-2', 1, 'Human Geography'),
    ('geography-2', 2, 'Population'),
    ('geography-2', 3, 'Settlement'),
    ('geography-2', 4, 'Agriculture'),
    ('geography-2', 5, 'Industry'),
    ('geography-2', 6, 'Transport and Communication'),
    ('geography-2', 7, 'Trade'),
    ('geography-2', 8, 'Natural Resources'),
    ('geography-2', 9, 'Regional Geography'),
    ('geography-2', 10, 'Geographic Information System'),

    ('logic-1', 1, 'Nature and Scope of Logic'),
    ('logic-1', 2, 'Terms'),
    ('logic-1', 3, 'Propositions'),
    ('logic-1', 4, 'Immediate Inference'),
    ('logic-1', 5, 'Categorical Syllogism'),
    ('logic-1', 6, 'Symbolic Logic'),
    ('logic-1', 7, 'Truth Tables'),
    ('logic-1', 8, 'Fallacies'),
    ('logic-1', 9, 'Scientific Method'),

    ('logic-2', 1, 'Induction'),
    ('logic-2', 2, 'Causation'),
    ('logic-2', 3, 'Analogy'),
    ('logic-2', 4, 'Hypothesis'),
    ('logic-2', 5, 'Probability'),
    ('logic-2', 6, 'Explanation'),
    ('logic-2', 7, 'Definition'),
    ('logic-2', 8, 'Division and Classification'),
    ('logic-2', 9, 'Mills Methods')
)
INSERT INTO public.chapters (
  subject_id,
  exam_type_id,
  group_id,
  name,
  order_index,
  readiness_status,
  is_active,
  updated_at
)
SELECT
  s.id,
  s.exam_type_id,
  s.group_id,
  seed.name,
  seed.order_index,
  'not_started',
  true,
  now()
FROM chapter_seed seed
JOIN public.subjects s
  ON s.slug = seed.subject_slug
WHERE NOT EXISTS (
  SELECT 1
  FROM public.chapters existing
  WHERE existing.subject_id = s.id
    AND lower(existing.name) = lower(seed.name)
);
